version: '3.8'

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  mariadb:
    driver: local
  docker-in-docker:
    driver: local

services:
### PHP-FPM ############################################
  php-fpm:
    image: ghcr.io/nulldark/php-fpm:8.3
    restart: always
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:${APP_CODE_CONTAINER_FLAGS}
      - ${APP_CODE_PATH_HOST}/dev/containers/php-fpm/php-fpm.d:/etc/php/8.3/php-fpm.d/
      - ${APP_CODE_PATH_HOST}/dev/containers/php-fpm/php.ini:/etc/php/8.3/php.ini
      - docker-in-docker:/certs/client
    expose:
      - "9000"
    networks:
      - internal
    links:
      - docker-in-docker
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
### nginx #############################################
  nginx:
    build:
      context: dev/containers/nginx
    restart: always
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:${APP_CODE_CONTAINER_FLAGS}
      - ${NGINX_LOG_PATH}:/var/log/nginx/
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available/
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl/
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - external
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
  ### MariaDB ##########################################
  mariadb:
    image: mariadb:11.3.1-rc
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - internal
### Docker in Docker ##################################
  docker-in-docker:
    image: docker:20.10-dind
    environment:
      DOCKER_TLS_SAN: DNS:docker-in-docker
    privileged: true
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - docker-in-docker:/certs/client
    expose:
      - 2375
    networks:
      - internal